### ISSUE TITLE
Je le dirais une seule fois mais c'est un peu degueulasse quand même

### ISSUE THREAD

**Issue by monsieurpigeon** [dezmou/useRender#1]
mais bon ça marche.

**Comment by dezmou** [comment]
Hello :) 

It appear that the issue does not follow the Modez's guideline 
 - no French 
 - no harassing content
 
The issues is closed and I am willing to pay you a decent amount of money if you promise to never speak to me again

**Comment by monsieurpigeon** [comment]
how much ?

**Comment by dezmou** [comment]
![alt text](https://media.makeameme.org/created/1-billion-dollars-5b063b.jpg "Title")

**Comment by monsieurpigeon** [comment]
my silence worth much much less

**Comment by dezmou** [comment]
then we won't have a deal

**Comment by monsieurpigeon** [comment]
🤷‍♂️
